<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_DrainValve" Id="{25dd2f0d-413f-4e46-84da-839092afc7e8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DrainValve EXTENDS FB_Pump
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{bd3990eb-1bce-4b32-8f9b-499236bfc38e}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[//FLOW RATE NITIALIZATION
rFlowRate	:= -30.0;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_DrainValve">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_DrainValve.FB_init">
      <LineId Id="13" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>